import { NextRequest } from 'next/server'
import { readFileSync } from 'fs'
import { join } from 'path'

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const docId = searchParams.get('docId')

  if (!docId) {
    return new Response('Document ID is required', { status: 400 })
  }

  try {
    // 读取文档数据
    const dataPath = join(process.cwd(), 'data', 'documents-data.json')
    const data = JSON.parse(readFileSync(dataPath, 'utf8'))
    
    // 查找指定文档
    const document = data.documents.find((doc: any) => doc.id === docId)
    
    if (!document) {
      return new Response('Document not found', { status: 404 })
    }

    // 优先返回文档的实际内容，如果没有内容则返回元数据
    let content;
    if (document.content) {
      content = document.content;
    } else {
      content = `JURISGUARD LEGAL DOCUMENT\n\n` +
        `Title: ${document.title}\n` +
        `ID: ${document.id}\n` +
        `Type: ${document.type}\n` +
        `Category: ${document.category}\n` +
        `Jurisdiction: ${document.jurisdiction || 'N/A'}\n` +
        `Author: ${document.author || 'N/A'}\n` +
        `Version: ${document.version || 'N/A'}\n` +
        `Status: ${document.status}\n` +
        `Last Modified: ${document.lastModified}\n` +
        `Review Date: ${document.reviewDate || 'N/A'}\n\n` +
        `DESCRIPTION:\n${document.description || 'No description available.'}\n\n` +
        `RELATED REGULATIONS:\n${(document.relatedRegulations || []).join(', ') || 'None'}\n\n` +
        `TAGS:\n${(document.tags || []).join(', ') || 'None'}\n\n` +
        `Generated by JurisGuard on ${new Date().toISOString()}\n` +
        `\n---\nThis is a generated document for compliance purposes.\nEnsure to verify information with official sources.`
    }

    // 创建响应
    const response = new Response(content, {
      headers: {
        'Content-Type': 'text/plain;charset=utf-8',
        'Content-Disposition': `attachment; filename="${document.title.replace(/\s+/g, '_').substring(0, 50)}.txt"`,
        'Content-Length': String(new Blob([content]).size),
      },
    })

    return response
  } catch (error) {
    console.error('Download error:', error)
    return new Response('Internal server error', { status: 500 })
  }
}